# Generated by Django 2.2.4 on 2020-09-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hiredate',
        ),
    ]
